version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: loboenparis80
    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-blog
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: blogdb
      DB_USER: root
      DB_PASSWORD: loboenparis80

volumes:
  mysql_data:
