version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-blog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  blog-app:
    build: .
    container_name: spring-blog
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/blogdb
      DB_USER: bloguser
      DB_PASSWORD: blogpass

volumes:
  mysql_data:
